version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: postgres_db
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PWD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - pg_data:/var/lib/postgresql/data

    app:
        build: ./
        container_name: app
        restart: always
        depends_on:
            - postgres
        env_file:
            - .env
        ports:
            - '${API_PORT}:3000'
        command: ['npm', 'run', 'start:prod']

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - '${REDIS_PORT}:6379'

volumes:
    pg_data:
