// transactions events
export const EVENT_TRANSACTION_CREATED = 'TRANSACTION_CREATED';
export const EVENT_TRANSACTION_UPDATED = 'TRANSACTION_UPDATED';
export const EVENT_TRANSACTION_DELETED = 'TRANSACTION_DELETED';
